// 元库 DDL 静态检查（R8 卡 1）：MySQL 库曾不可启动——三道死刑（多语句未开 / TEXT 进索引 1170 /
// TEXT 挂时间默认 1067，外加 TEXT 字面量默认 1101）且头注谎称「差异只三处」。没有活体 MySQL 可打，
// 按结构钉死这三类形状不再出现；sqlite 侧用内存库真跑一遍 DDL 当执行级证据。
// DDL 一种方言一个 .sql 文件，这里与 datasource.ts 同一路径读法（cwd 下 src/server/meta/ddl/）。

import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { SqliteDatasource, coercePgRow, ddlOf, metaDialectOf, openMetaDatasource, toPgPlaceholders } from "../server/meta/datasource";
import { insertIgnoreSql } from "../server/meta/stores/base";
import { MSG } from "../server/errors";

const SQLITE_DDL = ddlOf("sqlite");
const MYSQL_DDL = ddlOf("mysql");
const PG_DDL = ddlOf("pg");

describe("元库 DDL（三方言）", () => {
  it("sqlite DDL 在内存库真跑通过；adj_overlap 带按对唯一索引；onto_version 工作行唯一锚（draft_key）生效", () => {
    const db = new DatabaseSync(":memory:");
    db.exec(SQLITE_DDL); // 执行级：语法与约束都被 SQLite 真验过
    const idx = db.prepare(`SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'adj_overlap'`).all() as { name: string }[];
    expect(idx.length).toBeGreaterThan(0); // UNIQUE(workspace_id, class_a, class_b) 的自动索引
    db.prepare(`INSERT INTO onto_workspace (id, name) VALUES (1, 'ddlcheck')`).run(); // 外键前置：工作行挂在空间上
    // 工作行唯一锚：绕过 saveDraftPack 裸插第二工作行被 UNIQUE(draft_key) 拦（无状态化后「每空间恰一行」的 DB 级保证）
    db.prepare(`INSERT INTO onto_version (workspace_id, version, yaml, canvas_json, rev) VALUES (1, NULL, '', '{}', 0)`).run();
    expect(() => db.prepare(`INSERT INTO onto_version (workspace_id, version, yaml, canvas_json, rev) VALUES (1, NULL, '', '{}', 0)`).run()).toThrow(/UNIQUE/i);
    // 编号行不参与唯一锚：两个同空间不同编号行正常共存
    db.prepare(`INSERT INTO onto_version (workspace_id, version, yaml, canvas_json, rev) VALUES (1, 1, 'y', NULL, 0)`).run();
    db.prepare(`INSERT INTO onto_version (workspace_id, version, yaml, canvas_json, rev) VALUES (1, 2, 'y', NULL, 0)`).run();
    db.close();
  });

  it("MYSQL_DDL 不含三类致命形状（R8 卡 1 回归）", () => {
    expect(MYSQL_DDL).not.toMatch(/TEXT[^\n]*UNIQUE/); // TEXT 列进 UNIQUE（错误 1170）
    expect(MYSQL_DDL).not.toMatch(/name TEXT NOT NULL,\s*\n\s*PRIMARY KEY/); // TEXT 列进主键（错误 1170）
    expect(MYSQL_DDL).not.toMatch(/TEXT[^\n]*DEFAULT CURRENT_TIMESTAMP/); // TEXT 挂时间默认值（错误 1067）
    expect(MYSQL_DDL).not.toMatch(/TEXT NOT NULL DEFAULT '[^'(]/); // TEXT 字面量默认值（错误 1101，只许表达式形态 DEFAULT ('...')）
    // 键列与时列的正面对照：VARCHAR(191) 与 DATETIME 必须出现
    expect(MYSQL_DDL).toContain("name VARCHAR(191) NOT NULL UNIQUE");
    expect(MYSQL_DDL).toContain("created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP");
    expect(MYSQL_DDL).toContain("UNIQUE (workspace_id, class_a, class_b)");
    // 工作行唯一锚三方言同构：draft_key 生成列 + UNIQUE；rev 列持久化草稿修订号
    expect(MYSQL_DDL).toContain("draft_key BIGINT GENERATED ALWAYS AS");
    expect(MYSQL_DDL).toContain("UNIQUE KEY uq_draft_key");
    expect(MYSQL_DDL).toContain("rev INT NOT NULL DEFAULT 0");
    expect(SQLITE_DDL).toContain("draft_key INTEGER GENERATED ALWAYS AS");
    expect(SQLITE_DDL).toContain("UNIQUE (draft_key)");
    expect(SQLITE_DDL).toContain("rev INTEGER NOT NULL DEFAULT 0");
    expect(PG_DDL).toContain("draft_key BIGINT GENERATED ALWAYS AS");
    expect(PG_DDL).toContain("STORED");
    expect(PG_DDL).not.toMatch(/draft_key[^\n]*VIRTUAL/);
    expect(PG_DDL).toContain("CONSTRAINT uq_draft_key UNIQUE (draft_key)");
    expect(PG_DDL).toContain("rev INTEGER NOT NULL DEFAULT 0");
    // 发号器改雪花：meta_seq 表三方言都不存在
    expect(MYSQL_DDL).not.toContain("meta_seq");
    expect(SQLITE_DDL).not.toContain("meta_seq");
    expect(PG_DDL).not.toContain("meta_seq");
  });

  it("MysqlDatasource 建池开了 multipleStatements；PgDatasource 挂了空闲连接 error（九个 CREATE TABLE 一次下发 / 掉线不炸进程）", () => {
    const src = readFileSync("src/server/meta/datasource.ts", "utf8");
    expect(src).toContain("multipleStatements: true");
    expect(src).toContain('p.on("error"');
  });

  it("三方言的表集合一致（九张表同名同约束面）", () => {
    const tables = (ddl: string) => [...ddl.matchAll(/CREATE TABLE IF NOT EXISTS (\w+)/g)].map((m) => m[1]).sort();
    expect(tables(MYSQL_DDL)).toEqual(tables(SQLITE_DDL));
    expect(tables(PG_DDL)).toEqual(tables(SQLITE_DDL));
  });

  it("DDL 设计面：MySQL 每表 ENGINE/CHARSET + 表级 COMMENT；三方言外键与扫描索引齐备", () => {
    expect(MYSQL_DDL.match(/\) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4/g)?.length).toBe(9); // 九表各自声明（中文字段安全；带右括号只数表定义，头注不计）
    expect(MYSQL_DDL.match(/\) ENGINE=[^\n]*COMMENT='/g)?.length).toBe(9); // 九表各一句表级 COMMENT（注释投影纪律）
    expect(MYSQL_DDL.match(/FOREIGN KEY \(workspace_id\)/g)?.length).toBe(8); // 除 onto_workspace 自身：onto_version + 七张业务表
    expect(SQLITE_DDL.match(/REFERENCES onto_workspace\(id\)/g)?.length).toBe(8);
    expect(PG_DDL.match(/REFERENCES onto_workspace\(id\)/g)?.length).toBe(8);
    expect(PG_DDL).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(PG_DDL).toContain("TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP");
    expect(PG_DDL).not.toContain("ENGINE=InnoDB");
    // PG 注释载体是 COMMENT ON：九表各有表级注释，列注释投影同一份文本（与 MySQL 的 COMMENT 子句对齐维护）
    expect(PG_DDL.match(/COMMENT ON TABLE \w+ IS '/g)?.length).toBe(9);
    expect(PG_DDL).toContain("COMMENT ON COLUMN onto_version.draft_key IS '工作行唯一锚");
    expect(PG_DDL).toContain("COMMENT ON COLUMN adj_decision.verdict IS 'same | overlap | stage | name_similar | skip");
    // 空间维扫描的索引落点（UNIQUE/PK 左前缀已覆盖的不重复建）
    for (const idx of ["idx_adj_decision_ws", "idx_ont_question_ws", "idx_log_query_ws_time", "idx_log_action_ws_time"]) {
      expect(MYSQL_DDL).toContain(idx);
      expect(SQLITE_DDL).toContain(idx);
      expect(PG_DDL).toContain(idx);
    }
  });

  it("开发期不做老库迁移：打开即建表，CAS 与工作行唯一锚直接生效", async () => {
    const s = new SqliteDatasource(":memory:");
    try {
      await s.run(`INSERT INTO onto_workspace (id, name) VALUES (1, 'ws')`);
      await s.run(`INSERT INTO onto_version (workspace_id, version, yaml, canvas_json, rev) VALUES (1, NULL, '', '{}', 0)`);
      // CAS：命中 1 行，重放 0 行（冲突语义）
      await expect(s.run(`UPDATE onto_version SET canvas_json = '{"m":1}', rev = rev + 1 WHERE workspace_id = 1 AND version IS NULL AND rev = 0`)).resolves.toBe(1);
      await expect(s.run(`UPDATE onto_version SET canvas_json = '{"m":1}', rev = rev + 1 WHERE workspace_id = 1 AND version IS NULL AND rev = 0`)).resolves.toBe(0);
      // 工作行唯一锚：第二工作行被 UNIQUE 拦（「每空间恰一行」的 DB 级保证）
      await expect(s.run(`INSERT INTO onto_version (workspace_id, version, yaml, canvas_json, rev) VALUES (1, NULL, '', '{}', 0)`)).rejects.toThrow(/UNIQUE/i);
      // 发号器已改雪花：meta_seq 表不存在
      const tables = await s.all(`SELECT name FROM sqlite_master WHERE type = 'table' AND name = 'meta_seq'`);
      expect(tables).toHaveLength(0);
    } finally {
      await s.close();
    }
  });
});

describe("元库 DSN 与占位符", () => {
  it("metaDialectOf：空 = sqlite；mysql://；postgres:// 与 postgresql://；未知 scheme 抛 MSG", () => {
    expect(metaDialectOf(undefined)).toBe("sqlite");
    expect(metaDialectOf("")).toBe("sqlite");
    expect(metaDialectOf("mysql://u:p@h:3306/db")).toBe("mysql");
    expect(metaDialectOf("postgres://u:p@h:5432/db")).toBe("pg");
    expect(metaDialectOf("postgresql://u:p@h/db")).toBe("pg");
    expect(metaDialectOf("POSTGRES://h/db")).toBe("pg");
    expect(() => metaDialectOf("redis://h")).toThrow(MSG.metaDsnUnknown("redis"));
    expect(() => metaDialectOf("not-a-dsn")).toThrow(MSG.metaDsnUnknown(""));
  });

  it("toPgPlaceholders：? 按出现顺序换成 $n；无问号原样", () => {
    expect(toPgPlaceholders("SELECT * FROM t WHERE a = ? AND b = ?")).toBe("SELECT * FROM t WHERE a = $1 AND b = $2");
    expect(toPgPlaceholders("UPDATE ont_question SET status = ?, detail = ?, version = COALESCE(?, version) WHERE workspace_id = ? AND id = ?"))
      .toBe("UPDATE ont_question SET status = $1, detail = $2, version = COALESCE($3, version) WHERE workspace_id = $4 AND id = $5");
    expect(toPgPlaceholders("SELECT name FROM onto_workspace")).toBe("SELECT name FROM onto_workspace");
  });

  it("insertIgnoreSql 三方言形态", () => {
    const into = "onto_workspace (name, seed_from) VALUES (?, ?)";
    expect(insertIgnoreSql("mysql", into)).toBe(`INSERT IGNORE INTO ${into}`);
    expect(insertIgnoreSql("sqlite", into)).toBe(`INSERT OR IGNORE INTO ${into}`);
    expect(insertIgnoreSql("pg", into)).toBe(`INSERT INTO ${into} ON CONFLICT DO NOTHING`);
  });

  it("openMetaDatasource 不设 DSN 打开 SqliteDatasource", async () => {
    const b = openMetaDatasource(undefined, ":memory:");
    expect(b.dialect).toBe("sqlite");
    await b.close();
  });

  it("coercePgRow：int8 转 Number；时间 Date 转 ISO；null 不动；其它类型原样", () => {
    const fields = [
      { name: "id", dataTypeID: 20 },
      { name: "created_at", dataTypeID: 1184 },
      { name: "touched", dataTypeID: 1114 },
      { name: "note", dataTypeID: 25 },
      { name: "rev", dataTypeID: 23 },
    ];
    expect(coercePgRow(fields, {
      id: "12",
      created_at: new Date("2026-08-26T01:02:03.000Z"),
      touched: "2026-08-26 01:02:03",
      note: "x",
      rev: 3,
    })).toEqual({
      id: 12,
      created_at: "2026-08-26T01:02:03.000Z",
      touched: "2026-08-26 01:02:03",
      note: "x",
      rev: 3,
    });
    expect(coercePgRow(fields, { id: null, created_at: null, touched: null, note: null, rev: 0 }))
      .toEqual({ id: null, created_at: null, touched: null, note: null, rev: 0 });
  });
});
