-- 元库 DDL（PostgreSQL 方言）——建库单源：一种数据库一个文件（sqlite.sql / mysql.sql 同构手写，不做字符串替换派生）。
-- 开发期不做老库迁移：结构变了删库重建；启动只跑本文件的 CREATE TABLE IF NOT EXISTS（datasource.ts 读文件下发）。
-- 注释纪律：本文件的注释载体是 COMMENT ON（进系统目录，工具可查）；sqlite.sql 用行内 --（它是文本源），mysql.sql 用 COMMENT 子句——三边对齐维护。
-- 与 sqlite.sql 的方言差异（全部刻意，改之前先读这段）：
-- ① 自增列型 BIGINT GENERATED BY DEFAULT AS IDENTITY；② 浮点型 DOUBLE PRECISION；
-- ③ 时间列 TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP；
-- ④ 生成列 STORED（PG 12+ 没有 VIRTUAL；VIRTUAL 是 PG 18）；
-- ⑤ 工作行唯一锚写成 CONSTRAINT uq_draft_key（与 mysql.sql 的索引同名）；
-- ⑥ 索引单独成句（CREATE INDEX IF NOT EXISTS，同 SQLite；MySQL 无此语法，索引内联进表定义）。
-- TEXT 可以进 UNIQUE（无 MySQL 1170），name / class_a 与 sqlite 一样用 TEXT。
-- 外键三方言都声明：PG 天生生效。

CREATE TABLE IF NOT EXISTS onto_workspace (   -- 工作空间注册表：一个空间一行，只登记身份（画布内容全在 onto_version 的工作行）
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,                  -- 空间名（小写字母/数字/中划线/下划线）
  seed_from TEXT,                             -- 起步来源：template=演示模板；lazy=被元数据写抢注
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE onto_workspace IS '工作空间注册表：一个空间一行，只登记身份（画布内容全在 onto_version 的工作行）';
COMMENT ON COLUMN onto_workspace.id IS '空间 id';
COMMENT ON COLUMN onto_workspace.name IS '空间名（小写字母/数字/中划线/下划线）';
COMMENT ON COLUMN onto_workspace.seed_from IS '起步来源：template=演示模板；lazy=被元数据写抢注';
COMMENT ON COLUMN onto_workspace.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS onto_version (     -- 版本链 + 工作行：编号行是不可变历史；version IS NULL 的是工作行（每空间恰一行的可变头）
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  version INTEGER,                            -- 已发布编号（首版为 1）；NULL = 工作行
  yaml TEXT NOT NULL DEFAULT '',              -- 本体 YAML 全量快照（不存增量 diff）；工作行恒空串（内容在 canvas_json）
  canvas_json TEXT,                           -- 画布包 JSON：{ config, layout, edgeBends, edgePins }；老编号行可能没有
  origin TEXT NOT NULL DEFAULT 'publish',     -- 恒 publish（工作行带默认值，不读它）；rollback 行只见于历史库
  note TEXT,                                  -- 发布说明
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  rev INTEGER NOT NULL DEFAULT 0,             -- 工作行的草稿修订号（编号行恒 0，不读它）：CAS 冲突检测与 ETag 的源
  draft_key BIGINT GENERATED ALWAYS AS (CASE WHEN version IS NULL THEN workspace_id END) STORED, -- 工作行唯一锚（编号行为 NULL 不参与；STORED 是 PG 12+ 可移植形态）
  UNIQUE (workspace_id, version),             -- 编号行不重复；工作行靠 NULL 不参与约束
  CONSTRAINT uq_draft_key UNIQUE (draft_key)  -- 「每空间恰一行」的 DB 级保证（替代写队列）
);
COMMENT ON TABLE onto_version IS '版本链 + 工作行：编号行是不可变历史；version IS NULL 的是工作行（每空间恰一行的可变头）';
COMMENT ON COLUMN onto_version.id IS '行 id';
COMMENT ON COLUMN onto_version.workspace_id IS '所属空间';
COMMENT ON COLUMN onto_version.version IS '已发布编号（首版为 1）；NULL = 工作行';
COMMENT ON COLUMN onto_version.yaml IS '本体 YAML 全量快照（不存增量 diff）；工作行恒空串（内容在 canvas_json）';
COMMENT ON COLUMN onto_version.canvas_json IS '画布包 JSON：{ config, layout, edgeBends, edgePins }；老编号行可能没有';
COMMENT ON COLUMN onto_version.origin IS '恒 publish（工作行带默认值，不读它）；rollback 行只见于历史库';
COMMENT ON COLUMN onto_version.note IS '发布说明';
COMMENT ON COLUMN onto_version.created_at IS '创建时间';
COMMENT ON COLUMN onto_version.rev IS '工作行的草稿修订号（编号行恒 0，不读它）：CAS 冲突检测与 ETag 的源';
COMMENT ON COLUMN onto_version.draft_key IS '工作行唯一锚（编号行为 NULL 不参与；STORED 是 PG 12+ 可移植形态）';

CREATE TABLE IF NOT EXISTS conn_source (      -- 数据源连接：本体按 name 引用
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  name TEXT NOT NULL,                         -- 连接名
  type TEXT NOT NULL,                         -- mysql | pg | sqlite
  host TEXT,
  port INTEGER,
  db_name TEXT,
  ro_user TEXT,                               -- 只读账号：读表结构与问数用
  ro_pass TEXT,                               -- 密码明文存（演示期；加密为后续项）
  rw_user TEXT,                               -- 可写账号：动作写回用，可空
  rw_pass TEXT,                               -- 密码明文存（演示期；加密为后续项）
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, name)
);
COMMENT ON TABLE conn_source IS '数据源连接：本体按 name 引用';
COMMENT ON COLUMN conn_source.id IS '行 id';
COMMENT ON COLUMN conn_source.workspace_id IS '所属空间';
COMMENT ON COLUMN conn_source.name IS '连接名';
COMMENT ON COLUMN conn_source.type IS 'mysql | pg | sqlite';
COMMENT ON COLUMN conn_source.host IS '主机（sqlite 连接没有）';
COMMENT ON COLUMN conn_source.port IS '端口';
COMMENT ON COLUMN conn_source.db_name IS '库名；sqlite 连接是文件路径';
COMMENT ON COLUMN conn_source.ro_user IS '只读账号：读表结构与问数用';
COMMENT ON COLUMN conn_source.ro_pass IS '密码明文存（演示期；加密为后续项）';
COMMENT ON COLUMN conn_source.rw_user IS '可写账号：动作写回用，可空';
COMMENT ON COLUMN conn_source.rw_pass IS '密码明文存（演示期；加密为后续项）';
COMMENT ON COLUMN conn_source.created_at IS '创建时间';
COMMENT ON COLUMN conn_source.updated_at IS '最近改动时间（保存连接即刷新）';

CREATE TABLE IF NOT EXISTS adj_decision (     -- 裁决留痕：人定的，不可重算
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  version INTEGER,                            -- 结论生效的已发布版本，发布时回填
  class_a TEXT NOT NULL,                      -- 被裁决的两个类
  class_b TEXT NOT NULL,
  source_a TEXT NOT NULL,                     -- 两个类各自来自的连接
  source_b TEXT NOT NULL,
  llm_advice TEXT,                            -- 模型建议与依据
  rate DOUBLE PRECISION,                      -- 裁决时看到的交集率
  evidence TEXT,                              -- 证据快照 JSON：归一化规则、样本量、交集数；交集可重算，快照留裁决时点
  verdict TEXT NOT NULL,                      -- same | overlap | stage | name_similar | skip（同一 | 部分重叠 | 阶段 | 仅名称相似 | 跳过）
  decided_by TEXT NOT NULL,                   -- 裁决人
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE adj_decision IS '裁决留痕：人定的，不可重算';
COMMENT ON COLUMN adj_decision.id IS '行 id';
COMMENT ON COLUMN adj_decision.workspace_id IS '所属空间';
COMMENT ON COLUMN adj_decision.version IS '结论生效的已发布版本，发布时回填';
COMMENT ON COLUMN adj_decision.class_a IS '被裁决的两个类';
COMMENT ON COLUMN adj_decision.class_b IS '被裁决的两个类';
COMMENT ON COLUMN adj_decision.source_a IS '两个类各自来自的连接';
COMMENT ON COLUMN adj_decision.source_b IS '两个类各自来自的连接';
COMMENT ON COLUMN adj_decision.llm_advice IS '模型建议与依据';
COMMENT ON COLUMN adj_decision.rate IS '裁决时看到的交集率';
COMMENT ON COLUMN adj_decision.evidence IS '证据快照 JSON：归一化规则、样本量、交集数；交集可重算，快照留裁决时点';
COMMENT ON COLUMN adj_decision.verdict IS 'same | overlap | stage | name_similar | skip（同一 | 部分重叠 | 阶段 | 仅名称相似 | 跳过）';
COMMENT ON COLUMN adj_decision.decided_by IS '裁决人';
COMMENT ON COLUMN adj_decision.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS adj_overlap (      -- 交集计算记录：机器算的，可重算；只落计数，标识值集合不落盘
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  class_a TEXT NOT NULL,                      -- 被比对的两个类
  class_b TEXT NOT NULL,
  norm_rule TEXT,                             -- 归一化规则
  count_a INTEGER NOT NULL,                   -- 两类的标识数
  count_b INTEGER NOT NULL,
  count_hit INTEGER NOT NULL,                 -- 交集数
  rate DOUBLE PRECISION NOT NULL,             -- 交集率 = |交集| / max(|A|, |B|)
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (workspace_id, class_a, class_b)     -- 按对一行（并发重算不双行，upsert 落点）
);
COMMENT ON TABLE adj_overlap IS '交集计算记录：机器算的，可重算；只落计数，标识值集合不落盘';
COMMENT ON COLUMN adj_overlap.id IS '行 id';
COMMENT ON COLUMN adj_overlap.workspace_id IS '所属空间';
COMMENT ON COLUMN adj_overlap.class_a IS '被比对的两个类';
COMMENT ON COLUMN adj_overlap.class_b IS '被比对的两个类';
COMMENT ON COLUMN adj_overlap.norm_rule IS '归一化规则';
COMMENT ON COLUMN adj_overlap.count_a IS '两类的标识数';
COMMENT ON COLUMN adj_overlap.count_b IS '两类的标识数';
COMMENT ON COLUMN adj_overlap.count_hit IS '交集数';
COMMENT ON COLUMN adj_overlap.rate IS '交集率 = |交集| / max(|A|, |B|)';
COMMENT ON COLUMN adj_overlap.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS adj_candidates (   -- 候选对快照：模型提的，可重算；同一草稿内容只问一次模型
  workspace_id BIGINT PRIMARY KEY REFERENCES onto_workspace(id), -- 每空间恰一份快照
  shot_hash TEXT NOT NULL,                    -- 投喂形状（类名/连接集/字段名）的哈希：变了才重算
  proposals TEXT NOT NULL,                    -- 过筛后的候选对 JSON（PairAdvice[]；定案过滤在读时套）
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE adj_candidates IS '候选对快照：模型提的，可重算；同一草稿内容只问一次模型';
COMMENT ON COLUMN adj_candidates.workspace_id IS '所属空间（每空间恰一份快照）';
COMMENT ON COLUMN adj_candidates.shot_hash IS '投喂形状（类名/连接集/字段名）的哈希：变了才重算';
COMMENT ON COLUMN adj_candidates.proposals IS '过筛后的候选对 JSON（PairAdvice[]；定案过滤在读时套）';
COMMENT ON COLUMN adj_candidates.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS ont_question (     -- 验收问题集
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  version INTEGER,                            -- 最后一次跑批时的本体版本
  question TEXT NOT NULL,                     -- 自然语言问题
  expected TEXT,                              -- 纯数字=比对行数；字段=值=至少一行对上；留空=能查出就算过
  status TEXT NOT NULL DEFAULT '未跑',        -- 词表单源在 features/acceptance/questionStatus.ts 的 Q_STATUS（meta 不 import engine，按名互指）
  detail TEXT                                 -- 失败原因（白话），通过时清空
);
COMMENT ON TABLE ont_question IS '验收问题集';
COMMENT ON COLUMN ont_question.id IS '行 id';
COMMENT ON COLUMN ont_question.workspace_id IS '所属空间';
COMMENT ON COLUMN ont_question.version IS '最后一次跑批时的本体版本';
COMMENT ON COLUMN ont_question.question IS '自然语言问题';
COMMENT ON COLUMN ont_question.expected IS '纯数字=比对行数；字段=值=至少一行对上；留空=能查出就算过';
COMMENT ON COLUMN ont_question.status IS '词表单源在 features/acceptance/questionStatus.ts 的 Q_STATUS（meta 不 import engine，按名互指）';
COMMENT ON COLUMN ont_question.detail IS '失败原因（白话），通过时清空';

CREATE TABLE IF NOT EXISTS log_query (        -- 问数留痕：存请求与成败，不存结果集
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  version INTEGER,                            -- 查询依据的本体版本
  session_id TEXT,                            -- 关联的会话
  model TEXT,                                 -- 编查询用的模型（离线回退也记）
  question TEXT,                              -- 自然语言问题
  query_json TEXT,                            -- 编出的结构化查询
  row_count INTEGER,                          -- 当时返回的行数；不是结果集
  error TEXT,                                 -- 失败原因摘要
  duration_ms INTEGER,                        -- 耗时（毫秒）
  ok INTEGER NOT NULL,                        -- 1 成 0 败
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE log_query IS '问数留痕：存请求与成败，不存结果集';
COMMENT ON COLUMN log_query.id IS '行 id';
COMMENT ON COLUMN log_query.workspace_id IS '所属空间';
COMMENT ON COLUMN log_query.version IS '查询依据的本体版本';
COMMENT ON COLUMN log_query.session_id IS '关联的会话';
COMMENT ON COLUMN log_query.model IS '编查询用的模型（离线回退也记）';
COMMENT ON COLUMN log_query.question IS '自然语言问题';
COMMENT ON COLUMN log_query.query_json IS '编出的结构化查询';
COMMENT ON COLUMN log_query.row_count IS '当时返回的行数；不是结果集';
COMMENT ON COLUMN log_query.error IS '失败原因摘要';
COMMENT ON COLUMN log_query.duration_ms IS '耗时（毫秒）';
COMMENT ON COLUMN log_query.ok IS '1 成 0 败';
COMMENT ON COLUMN log_query.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS log_action (       -- 动作留痕
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id BIGINT NOT NULL REFERENCES onto_workspace(id),
  version INTEGER,                            -- 动作依据的本体版本
  action TEXT NOT NULL,                       -- 动作名
  object_type TEXT NOT NULL,                  -- 类名
  subject TEXT NOT NULL,                      -- 请求点名的个体识别值
  request_json TEXT,                          -- 请求参数
  projections TEXT,                           -- 各条写回的成败 JSON；演示期不拆子表
  error TEXT,                                 -- 前置/公理拒绝的原因；拒绝发生在写回之前
  duration_ms INTEGER,                        -- 耗时（毫秒）
  ok INTEGER NOT NULL,                        -- 1 成 0 败
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE log_action IS '动作留痕';
COMMENT ON COLUMN log_action.id IS '行 id';
COMMENT ON COLUMN log_action.workspace_id IS '所属空间';
COMMENT ON COLUMN log_action.version IS '动作依据的本体版本';
COMMENT ON COLUMN log_action.action IS '动作名';
COMMENT ON COLUMN log_action.object_type IS '类名';
COMMENT ON COLUMN log_action.subject IS '请求点名的个体识别值';
COMMENT ON COLUMN log_action.request_json IS '请求参数';
COMMENT ON COLUMN log_action.projections IS '各条写回的成败 JSON；演示期不拆子表';
COMMENT ON COLUMN log_action.error IS '前置/公理拒绝的原因；拒绝发生在写回之前';
COMMENT ON COLUMN log_action.duration_ms IS '耗时（毫秒）';
COMMENT ON COLUMN log_action.ok IS '1 成 0 败';
COMMENT ON COLUMN log_action.created_at IS '创建时间';

-- 空间维扫描的索引（UNIQUE/PK 左前缀已覆盖的不重复建）：PG 支持 IF NOT EXISTS，幂等由它兜
CREATE INDEX IF NOT EXISTS idx_adj_decision_ws ON adj_decision (workspace_id);
CREATE INDEX IF NOT EXISTS idx_ont_question_ws ON ont_question (workspace_id);
CREATE INDEX IF NOT EXISTS idx_log_query_ws_time ON log_query (workspace_id, created_at);
CREATE INDEX IF NOT EXISTS idx_log_action_ws_time ON log_action (workspace_id, created_at);
